language: rust
rust: 1.38.0
dist: bionic

before_script:
  - rustup target add wasm32-unknown-unknown

addons:
  apt:
    sources:
      - sourceline: "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
      - clang-8
      - libc6-dev-i386
  homebrew:
    packages:
      - llvm
    update: true

matrix:
  include:
    - name: Build on Linux
      os: linux
      script:
        - export PATH=/usr/lib/llvm-8/bin:$PATH
        - cargo build
        - cargo build --target=wasm32-unknown-unknown
        - cd bins && cargo build
        - git diff --exit-code Cargo.lock
    - name: Test
      os: linux
      script:
        - export PATH=/usr/lib/llvm-8/bin:$PATH
        - cargo test
