[package]
name = "ckb-standalone-debugger"
version = "0.1.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ckb-types = { git = "https://github.com/nervosnetwork/ckb", rev = "565ba0c" }
faster-hex = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_plain = "0.3.0"

js-sys = "0.3.27"
wasm-bindgen = "0.2.50"

[dependencies.ckb-sdk-types]
git = "https://github.com/nervosnetwork/ckb-cli"
rev = "6fc7cfd"
default-features = false
features = []

[dependencies.ckb-script]
git = "https://github.com/nervosnetwork/ckb"
rev = "565ba0c"
default-features = false
features = []

[dev-dependencies]
byteorder = "1.3.2"
