[package]
name = "ckb-standalone-debugger"
version = "0.3.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
exclude = ["bins", "js"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ckb-error = "0.37.0"
ckb-traits = "0.37.0"
ckb-types = "0.37.0"
ckb-jsonrpc-types = "0.37.0"
faster-hex = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_plain = "0.3.0"

js-sys = "0.3.27"
wasm-bindgen = "0.2.50"

[dependencies.ckb-script]
version = "0.37.0"
default-features = false
features = ["detect-asm"]

[dev-dependencies]
byteorder = "1.3.2"
