[package]
name = "ckb-debugger-binaries"
version = "0.4.1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
autobins = false

[[bin]]
name = "ckb-debugger"
path = "src/main.rs"

[dependencies]
clap = "2.33.0"
ckb-script = "0.42.0"
ckb-standalone-debugger = { path = ".." }
ckb-types = "0.42.0"
ckb-vm = { version = "0.19.2", features = ["detect-asm"] }
ckb-vm-debug-utils = { git = "https://github.com/xxuejie/ckb-vm-debug-utils", rev = "f6e3605" }
env_logger = "0.4.3"
faster-hex = "0.4.0"
gdb-remote-protocol = { git = "https://github.com/luser/rust-gdb-remote-protocol", rev = "565ab0c" }
log = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_plain = "0.3.0"
